//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Creobe.VoiceMemos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Creobe.VoiceMemos.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any ideas or suggestions, please let us know via email (beta@creobe.com)..
        /// </summary>
        public static string AboutBetaText {
            get {
                return ResourceManager.GetString("AboutBetaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutMenuItemText {
            get {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any ideas or suggestions, please let us know via email (voicememos@creobe.com) or just drop by our Facebook page (facebook.com/voicememos)..
        /// </summary>
        public static string AboutReleaseText {
            get {
                return ResourceManager.GetString("AboutReleaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string AccountConnectedStatusText {
            get {
                return ResourceManager.GetString("AccountConnectedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string AccountDisconnectConfirmMessageCaption {
            get {
                return ResourceManager.GetString("AccountDisconnectConfirmMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to disconnect this account?.
        /// </summary>
        public static string AccountDisconnectConfirmMessageText {
            get {
                return ResourceManager.GetString("AccountDisconnectConfirmMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disconnected.
        /// </summary>
        public static string AccountDisconnectedMessageCaption {
            get {
                return ResourceManager.GetString("AccountDisconnectedMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t connected your {0} account. Would you like to connect to {0} now?.
        /// </summary>
        public static string AccountDisconnectedMessageText {
            get {
                return ResourceManager.GetString("AccountDisconnectedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        public static string AccountDisconnectedStatusText {
            get {
                return ResourceManager.GetString("AccountDisconnectedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to couldn&apos;t get account status.
        /// </summary>
        public static string AccountErrorStatusText {
            get {
                return ResourceManager.GetString("AccountErrorStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountSettingsButtonText {
            get {
                return ResourceManager.GetString("AccountSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive, Soundcloud, others.
        /// </summary>
        public static string AccountSettingsHelpText {
            get {
                return ResourceManager.GetString("AccountSettingsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountSettingsViewTitle {
            get {
                return ResourceManager.GetString("AccountSettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checking account status....
        /// </summary>
        public static string AccountStatusCheckingText {
            get {
                return ResourceManager.GetString("AccountStatusCheckingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        public static string AccountUnknownStatusText {
            get {
                return ResourceManager.GetString("AccountUnknownStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add location.
        /// </summary>
        public static string AddLocationCheckboxText {
            get {
                return ResourceManager.GetString("AddLocationCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds your current location to memos. Memos with location can be viewed on a map..
        /// </summary>
        public static string AddLocationHelpText {
            get {
                return ResourceManager.GetString("AddLocationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add marker.
        /// </summary>
        public static string AddMarkerButtonText {
            get {
                return ResourceManager.GetString("AddMarkerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resolving address....
        /// </summary>
        public static string AddressFindingText {
            get {
                return ResourceManager.GetString("AddressFindingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not resolve address.
        /// </summary>
        public static string AddressUnidentifiedText {
            get {
                return ResourceManager.GetString("AddressUnidentifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +fav.
        /// </summary>
        public static string AddToFavoriteButtonText {
            get {
                return ResourceManager.GetString("AddToFavoriteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All memos added to favorites..
        /// </summary>
        public static string AddToFavoriteMultipleSuccessMessageText {
            get {
                return ResourceManager.GetString("AddToFavoriteMultipleSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string AddToFavoriteSuccessMessageCaption {
            get {
                return ResourceManager.GetString("AddToFavoriteSuccessMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOICE MEMOS.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available free space: {0}.
        /// </summary>
        public static string AvailableStorageText {
            get {
                return ResourceManager.GetString("AvailableStorageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BackspaceKeyText {
            get {
                return ResourceManager.GetString("BackspaceKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BuildLabelText {
            get {
                return ResourceManager.GetString("BuildLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait....
        /// </summary>
        public static string BusyMessageText {
            get {
                return ResourceManager.GetString("BusyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelMessageCaption {
            get {
                return ResourceManager.GetString("CancelMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will cancel the current recording..
        /// </summary>
        public static string CancelMessageText {
            get {
                return ResourceManager.GetString("CancelMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log.
        /// </summary>
        public static string ChangeLogButtonText {
            get {
                return ResourceManager.GetString("ChangeLogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change pin.
        /// </summary>
        public static string ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change pin.
        /// </summary>
        public static string ChangePasswordViewTitle {
            get {
                return ResourceManager.GetString("ChangePasswordViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string ChannelsLabelText {
            get {
                return ResourceManager.GetString("ChannelsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string ChannelsMonoText {
            get {
                return ResourceManager.GetString("ChannelsMonoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string ChannelsStereoText {
            get {
                return ResourceManager.GetString("ChannelsStereoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear in-app purchases.
        /// </summary>
        public static string ClearIapMenuItemText {
            get {
                return ResourceManager.GetString("ClearIapMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload to.
        /// </summary>
        public static string CloudServicesListLabelText {
            get {
                return ResourceManager.GetString("CloudServicesListLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm before canceling a recording.
        /// </summary>
        public static string ConfirmCancelCheckboxText {
            get {
                return ResourceManager.GetString("ConfirmCancelCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConfirmCancelMessageCaption {
            get {
                return ResourceManager.GetString("ConfirmCancelMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to cancel this recording?.
        /// </summary>
        public static string ConfirmCancelMessageText {
            get {
                return ResourceManager.GetString("ConfirmCancelMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm before deleting a memo.
        /// </summary>
        public static string ConfirmDeleteCheckboxText {
            get {
                return ResourceManager.GetString("ConfirmDeleteCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm pin.
        /// </summary>
        public static string ConfirmPasswordLabelText {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@creobe.com.
        /// </summary>
        public static string ContactSupportEmail {
            get {
                return ResourceManager.GetString("ContactSupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Creobe Ltd..
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current pin.
        /// </summary>
        public static string CurrentPasswordLabelText {
            get {
                return ResourceManager.GetString("CurrentPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string DateButtonText {
            get {
                return ResourceManager.GetString("DateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteMenuItemText {
            get {
                return ResourceManager.GetString("DeleteMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMessageCaption {
            get {
                return ResourceManager.GetString("DeleteMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the selected memos?.
        /// </summary>
        public static string DeleteMultipleMessageText {
            get {
                return ResourceManager.GetString("DeleteMultipleMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this memo?.
        /// </summary>
        public static string DeleteSingleMessageText {
            get {
                return ResourceManager.GetString("DeleteSingleMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DescriptionLabelText {
            get {
                return ResourceManager.GetString("DescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit memo before saving.
        /// </summary>
        public static string EditDetailsCheckboxText {
            get {
                return ResourceManager.GetString("EditDetailsCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you edit memo information before it is saved..
        /// </summary>
        public static string EditDetailsHelpText {
            get {
                return ResourceManager.GetString("EditDetailsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditMenuItemText {
            get {
                return ResourceManager.GetString("EditMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding format.
        /// </summary>
        public static string EncodingFormatLabelText {
            get {
                return ResourceManager.GetString("EncodingFormatLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding quality.
        /// </summary>
        public static string EncodingQualityLabelText {
            get {
                return ResourceManager.GetString("EncodingQualityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t favorited any memos..
        /// </summary>
        public static string FavoritesListEmptyText {
            get {
                return ResourceManager.GetString("FavoritesListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesTileTitle {
            get {
                return ResourceManager.GetString("FavoritesTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavoritesViewTitle {
            get {
                return ResourceManager.GetString("FavoritesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available in this beta release..
        /// </summary>
        public static string FeatureNotAvailableInBetaText {
            get {
                return ResourceManager.GetString("FeatureNotAvailableInBetaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to premium.
        /// </summary>
        public static string FeatureNotAvailableMessageCaption {
            get {
                return ResourceManager.GetString("FeatureNotAvailableMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available in Voice Memos Premium. Would you like to upgrade to Voice Memos Premium now?.
        /// </summary>
        public static string FeatureNotAvailableMessageText {
            get {
                return ResourceManager.GetString("FeatureNotAvailableMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@creobe.com.
        /// </summary>
        public static string FeatureRequestEmail {
            get {
                return ResourceManager.GetString("FeatureRequestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackMessageCancelButtonText {
            get {
                return ResourceManager.GetString("FeedbackMessageCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackMessageCaption {
            get {
                return ResourceManager.GetString("FeedbackMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackMessageGiveButtonText {
            get {
                return ResourceManager.GetString("FeedbackMessageGiveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate Voice Memos.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessageText {
            get {
                return ResourceManager.GetString("FeedbackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string GeneralSettingsButtonText {
            get {
                return ResourceManager.GetString("GeneralSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playback, tiles, prompts, others.
        /// </summary>
        public static string GeneralSettingsHelpText {
            get {
                return ResourceManager.GetString("GeneralSettingsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string GeneralSettingsViewTitle {
            get {
                return ResourceManager.GetString("GeneralSettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide notes.
        /// </summary>
        public static string HideNotesButtonText {
            get {
                return ResourceManager.GetString("HideNotesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions of this app uses L.A.M.E encoding engine v3.99  (http://lame.sf.net)..
        /// </summary>
        public static string LameMp3InfoText {
            get {
                return ResourceManager.GetString("LameMp3InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string ListButtonText {
            get {
                return ResourceManager.GetString("ListButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationButtonText {
            get {
                return ResourceManager.GetString("LocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finding location....
        /// </summary>
        public static string LocationFindingText {
            get {
                return ResourceManager.GetString("LocationFindingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to get your location.
        /// </summary>
        public static string LocationNotFoundText {
            get {
                return ResourceManager.GetString("LocationNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string MapButtonText {
            get {
                return ResourceManager.GetString("MapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show on map.
        /// </summary>
        public static string MapMenuItemText {
            get {
                return ResourceManager.GetString("MapMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing to show here. Record or tag some memos..
        /// </summary>
        public static string MemoListEmptyText {
            get {
                return ResourceManager.GetString("MemoListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string MemoListPivotHeadingAllText {
            get {
                return ResourceManager.GetString("MemoListPivotHeadingAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo {0}.
        /// </summary>
        public static string MemoNameTemplate {
            get {
                return ResourceManager.GetString("MemoNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New pin.
        /// </summary>
        public static string NewPasswordLabelText {
            get {
                return ResourceManager.GetString("NewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string NotImplementedMessageCaption {
            get {
                return ResourceManager.GetString("NotImplementedMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not available in this beta release..
        /// </summary>
        public static string NotImplementedMessageText {
            get {
                return ResourceManager.GetString("NotImplementedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string NumericKeyEightText {
            get {
                return ResourceManager.GetString("NumericKeyEightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string NumericKeyFiveText {
            get {
                return ResourceManager.GetString("NumericKeyFiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string NumericKeyFourText {
            get {
                return ResourceManager.GetString("NumericKeyFourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string NumericKeyNineText {
            get {
                return ResourceManager.GetString("NumericKeyNineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string NumericKeyOneText {
            get {
                return ResourceManager.GetString("NumericKeyOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string NumericKeySevenText {
            get {
                return ResourceManager.GetString("NumericKeySevenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string NumericKeySixText {
            get {
                return ResourceManager.GetString("NumericKeySixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string NumericKeyThreeText {
            get {
                return ResourceManager.GetString("NumericKeyThreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string NumericKeyTwoText {
            get {
                return ResourceManager.GetString("NumericKeyTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string NumericKeyZeroText {
            get {
                return ResourceManager.GetString("NumericKeyZeroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More apps by Creobe.
        /// </summary>
        public static string OtherAppsButtonText {
            get {
                return ResourceManager.GetString("OtherAppsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string PasswordIncorrectMessageCaption {
            get {
                return ResourceManager.GetString("PasswordIncorrectMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current pin is incorrect..
        /// </summary>
        public static string PasswordIncorrectMessageText {
            get {
                return ResourceManager.GetString("PasswordIncorrectMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string PasswordNoMatchMessageCaption {
            get {
                return ResourceManager.GetString("PasswordNoMatchMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new pin and confirmation pin do not match..
        /// </summary>
        public static string PasswordNoMatchMessageText {
            get {
                return ResourceManager.GetString("PasswordNoMatchMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string PasswordShortMessageCaption {
            get {
                return ResourceManager.GetString("PasswordShortMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new pin must be at least 4 characters long..
        /// </summary>
        public static string PasswordShortMessageText {
            get {
                return ResourceManager.GetString("PasswordShortMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter pin.
        /// </summary>
        public static string PasswordWaterMarkText {
            get {
                return ResourceManager.GetString("PasswordWaterMarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string PauseButtonText {
            get {
                return ResourceManager.GetString("PauseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        public static string PausedStatusText {
            get {
                return ResourceManager.GetString("PausedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin favorites.
        /// </summary>
        public static string PinFavoritesMenuItemText {
            get {
                return ResourceManager.GetString("PinFavoritesMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin memo.
        /// </summary>
        public static string PinMemoMenuItemText {
            get {
                return ResourceManager.GetString("PinMemoMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin record.
        /// </summary>
        public static string PinRecordMenuItemText {
            get {
                return ResourceManager.GetString("PinRecordMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin tag.
        /// </summary>
        public static string PinTagMenuItemText {
            get {
                return ResourceManager.GetString("PinTagMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string PlayButtonText {
            get {
                return ResourceManager.GetString("PlayButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ADs (advertisements)..
        /// </summary>
        public static string PremiumFeature1Text {
            get {
                return ResourceManager.GetString("PremiumFeature1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3 Recording. Memos recorded in MP3 format are 75% smaller than Wave format..
        /// </summary>
        public static string PremiumFeature2Text {
            get {
                return ResourceManager.GetString("PremiumFeature2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background recording. Take notes, browse the internet, do some math, or anything you want, while still recording..
        /// </summary>
        public static string PremiumFeature3Text {
            get {
                return ResourceManager.GetString("PremiumFeature3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect your memos with a pin code..
        /// </summary>
        public static string PremiumFeature4Text {
            get {
                return ResourceManager.GetString("PremiumFeature4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and share the link with Messaging, Email, or post it to social networks..
        /// </summary>
        public static string PremiumFeature5Text {
            get {
                return ResourceManager.GetString("PremiumFeature5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High quality stereo audio recording..
        /// </summary>
        public static string PremiumFeature6Text {
            get {
                return ResourceManager.GetString("PremiumFeature6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string QualityHighText {
            get {
                return ResourceManager.GetString("QualityHighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QualityLabelText {
            get {
                return ResourceManager.GetString("QualityLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string QualityLowText {
            get {
                return ResourceManager.GetString("QualityLowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string QualityMediumText {
            get {
                return ResourceManager.GetString("QualityMediumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Voice Memos.
        /// </summary>
        public static string RateButtonText {
            get {
                return ResourceManager.GetString("RateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingMessageCancelButtonText {
            get {
                return ResourceManager.GetString("RatingMessageCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying Voice Memos?.
        /// </summary>
        public static string RatingMessageCaption {
            get {
                return ResourceManager.GetString("RatingMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingMessageRateButtonText {
            get {
                return ResourceManager.GetString("RatingMessageRateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars.
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessageText {
            get {
                return ResourceManager.GetString("RatingMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ready.
        /// </summary>
        public static string ReadyStatusText {
            get {
                return ResourceManager.GetString("ReadyStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentLabelText {
            get {
                return ResourceManager.GetString("RecentLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing to show here. Your most recently recorded memos will appear here..
        /// </summary>
        public static string RecentListEmptyText {
            get {
                return ResourceManager.GetString("RecentListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        public static string RecordButtonText {
            get {
                return ResourceManager.GetString("RecordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record in background.
        /// </summary>
        public static string RecordInBackgroundCheckboxText {
            get {
                return ResourceManager.GetString("RecordInBackgroundCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continues recording when the app is in background. Your phone&apos;s location services must be enabled for this feature to work..
        /// </summary>
        public static string RecordInBackgroundHelpText {
            get {
                return ResourceManager.GetString("RecordInBackgroundHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recording.
        /// </summary>
        public static string RecordingSettingsButtonText {
            get {
                return ResourceManager.GetString("RecordingSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set recording quality, enhancements, others.
        /// </summary>
        public static string RecordingSettingsHelpText {
            get {
                return ResourceManager.GetString("RecordingSettingsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recording.
        /// </summary>
        public static string RecordingSettingsViewTitle {
            get {
                return ResourceManager.GetString("RecordingSettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recording.
        /// </summary>
        public static string RecordingStatusText {
            get {
                return ResourceManager.GetString("RecordingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string RecordTileTitle {
            get {
                return ResourceManager.GetString("RecordTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record under lockscreen.
        /// </summary>
        public static string RecordUnderLockCheckboxText {
            get {
                return ResourceManager.GetString("RecordUnderLockCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continues recording when the screen is locked..
        /// </summary>
        public static string RecordUnderLockHelpText {
            get {
                return ResourceManager.GetString("RecordUnderLockHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover lost memos.
        /// </summary>
        public static string RecoverButtonText {
            get {
                return ResourceManager.GetString("RecoverButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovers any memos you might have lost due to a crash, forced exit, or an update to the app..
        /// </summary>
        public static string RecoverHelpText {
            get {
                return ResourceManager.GetString("RecoverHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -fav.
        /// </summary>
        public static string RemoveFromFavoriteButtonText {
            get {
                return ResourceManager.GetString("RemoveFromFavoriteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string RemoveMenuItemText {
            get {
                return ResourceManager.GetString("RemoveMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove pin.
        /// </summary>
        public static string RemovePasswordViewTitle {
            get {
                return ResourceManager.GetString("RemovePasswordViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string ReportBugButtonText {
            get {
                return ResourceManager.GetString("ReportBugButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta@creobe.com.
        /// </summary>
        public static string ReportBugEmail {
            get {
                return ResourceManager.GetString("ReportBugEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report a bug.
        /// </summary>
        public static string ReportBugMenuItemText {
            get {
                return ResourceManager.GetString("ReportBugMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string RequirePasswordSwitchHeader {
            get {
                return ResourceManager.GetString("RequirePasswordSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset application data.
        /// </summary>
        public static string ResetDataButtonText {
            get {
                return ResourceManager.GetString("ResetDataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResetDataWarningMessageCaption {
            get {
                return ResourceManager.GetString("ResetDataWarningMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all your data and exit the app..
        /// </summary>
        public static string ResetDataWarningMessageText {
            get {
                return ResourceManager.GetString("ResetDataWarningMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: This will delete all your memos, cloud accounts, settings, and remove pin lock if enabled..
        /// </summary>
        public static string ResetDataWarningText {
            get {
                return ResourceManager.GetString("ResetDataWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string ResumeButtonText {
            get {
                return ResourceManager.GetString("ResumeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string SaveToMediaFailedMessageCaption {
            get {
                return ResourceManager.GetString("SaveToMediaFailedMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save to music.
        /// </summary>
        public static string SaveToMediaMenuItemText {
            get {
                return ResourceManager.GetString("SaveToMediaMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save some memos to music..
        /// </summary>
        public static string SaveToMediaMultipleFailedMessageText {
            get {
                return ResourceManager.GetString("SaveToMediaMultipleFailedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected memos saved to music..
        /// </summary>
        public static string SaveToMediaMultipleSuccessMessageText {
            get {
                return ResourceManager.GetString("SaveToMediaMultipleSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save memo to music..
        /// </summary>
        public static string SaveToMediaSingleFailedMessageText {
            get {
                return ResourceManager.GetString("SaveToMediaSingleFailedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo saved to music..
        /// </summary>
        public static string SaveToMediaSingleSuccessMessageText {
            get {
                return ResourceManager.GetString("SaveToMediaSingleSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SaveToMediaSuccessMessageCaption {
            get {
                return ResourceManager.GetString("SaveToMediaSuccessMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security.
        /// </summary>
        public static string SecuritySettingsButtonText {
            get {
                return ResourceManager.GetString("SecuritySettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setup your Voice Memos pin code.
        /// </summary>
        public static string SecuritySettingsHelpText {
            get {
                return ResourceManager.GetString("SecuritySettingsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security.
        /// </summary>
        public static string SecuritySettingsViewTitle {
            get {
                return ResourceManager.GetString("SecuritySettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectButtonText {
            get {
                return ResourceManager.GetString("SelectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set pin.
        /// </summary>
        public static string SetPasswordViewTitle {
            get {
                return ResourceManager.GetString("SetPasswordViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuItemText {
            get {
                return ResourceManager.GetString("SettingsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload + share....
        /// </summary>
        public static string ShareMenuItemText {
            get {
                return ResourceManager.GetString("ShareMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this Voice Memo I recorded..
        /// </summary>
        public static string ShareMethodEmailSubject {
            get {
                return ResourceManager.GetString("ShareMethodEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ShareMethodEmailText {
            get {
                return ResourceManager.GetString("ShareMethodEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share link.
        /// </summary>
        public static string ShareMethodLinkText {
            get {
                return ResourceManager.GetString("ShareMethodLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        public static string ShareMethodMessagingText {
            get {
                return ResourceManager.GetString("ShareMethodMessagingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this Voice Memo I recorded..
        /// </summary>
        public static string ShareMethodSocialMessage {
            get {
                return ResourceManager.GetString("ShareMethodSocialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload only.
        /// </summary>
        public static string ShareMethodUploadText {
            get {
                return ResourceManager.GetString("ShareMethodUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share with.
        /// </summary>
        public static string SharingMethodsListLabelText {
            get {
                return ResourceManager.GetString("SharingMethodsListLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show notes.
        /// </summary>
        public static string ShowNotesButtonText {
            get {
                return ResourceManager.GetString("ShowNotesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unplayed count on main tile.
        /// </summary>
        public static string ShowUnplayedCountCheckboxText {
            get {
                return ResourceManager.GetString("ShowUnplayedCountCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip silence.
        /// </summary>
        public static string SkipSilenceButtonText {
            get {
                return ResourceManager.GetString("SkipSilenceButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip silence.
        /// </summary>
        public static string SkipSilenceCheckboxText {
            get {
                return ResourceManager.GetString("SkipSilenceCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses recording if there is not audible sound..
        /// </summary>
        public static string SkipSilenceHelpText {
            get {
                return ResourceManager.GetString("SkipSilenceHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive.
        /// </summary>
        public static string SkyDriveNameText {
            get {
                return ResourceManager.GetString("SkyDriveNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundCloud.
        /// </summary>
        public static string SoundCloudNameText {
            get {
                return ResourceManager.GetString("SoundCloudNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storage.
        /// </summary>
        public static string StorageSettingsButtonText {
            get {
                return ResourceManager.GetString("StorageSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recover memos, save space, reset data.
        /// </summary>
        public static string StorageSettingsHelpText {
            get {
                return ResourceManager.GetString("StorageSettingsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storage.
        /// </summary>
        public static string StorageSettingsViewTitle {
            get {
                return ResourceManager.GetString("StorageSettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact support.
        /// </summary>
        public static string SupportButtonText {
            get {
                return ResourceManager.GetString("SupportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t tagged any memos yet. Tags will appear here when memos are tagged. You can tap a tag to see memos tagged with it..
        /// </summary>
        public static string TagListEmptyText {
            get {
                return ResourceManager.GetString("TagListEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string TagListPivotHeadingText {
            get {
                return ResourceManager.GetString("TagListPivotHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string TagsButtonText {
            get {
                return ResourceManager.GetString("TagsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsLabelText {
            get {
                return ResourceManager.GetString("TagsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleLabelText {
            get {
                return ResourceManager.GetString("TitleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin favorites.
        /// </summary>
        public static string UnPinFavoritesMenuItemText {
            get {
                return ResourceManager.GetString("UnPinFavoritesMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin memo.
        /// </summary>
        public static string UnPinMemoMenuItemText {
            get {
                return ResourceManager.GetString("UnPinMemoMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin record.
        /// </summary>
        public static string UnPinRecordMenuItemText {
            get {
                return ResourceManager.GetString("UnPinRecordMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin tag.
        /// </summary>
        public static string UnPinTagMenuItemText {
            get {
                return ResourceManager.GetString("UnPinTagMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade to premium....
        /// </summary>
        public static string UpgradeMenuItemText {
            get {
                return ResourceManager.GetString("UpgradeMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Memos Premium upgrade is a one-time purchase and will be FREE for this beta program..
        /// </summary>
        public static string UpgradeMessageBetaFooter {
            get {
                return ResourceManager.GetString("UpgradeMessageBetaFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not now.
        /// </summary>
        public static string UpgradeMessageCancelButtonText {
            get {
                return ResourceManager.GetString("UpgradeMessageCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to premium.
        /// </summary>
        public static string UpgradeMessageCaption {
            get {
                return ResourceManager.GetString("UpgradeMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Memos Premium upgrade is a one-time purchase and will cost you {0}..
        /// </summary>
        public static string UpgradeMessageFooter {
            get {
                return ResourceManager.GetString("UpgradeMessageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to premium and get these additional features and benefits:.
        /// </summary>
        public static string UpgradeMessageText {
            get {
                return ResourceManager.GetString("UpgradeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade.
        /// </summary>
        public static string UpgradeMessageUpgradeButtonText {
            get {
                return ResourceManager.GetString("UpgradeMessageUpgradeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string UpgradeSuccessMessageCaption {
            get {
                return ResourceManager.GetString("UpgradeSuccessMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Memos is now upgraded to Voice Memos Premium. You can now enjoy all the features without any limitations..
        /// </summary>
        public static string UpgradeSuccessMessageText {
            get {
                return ResourceManager.GetString("UpgradeSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UploadCancelMessageCaption {
            get {
                return ResourceManager.GetString("UploadCancelMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this upload?.
        /// </summary>
        public static string UploadCancelMessageText {
            get {
                return ResourceManager.GetString("UploadCancelMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string UploadFailedMessageCaption {
            get {
                return ResourceManager.GetString("UploadFailedMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload to {0}..
        /// </summary>
        public static string UploadFailedMessageText {
            get {
                return ResourceManager.GetString("UploadFailedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a while depending on the memo size. If it is taking too long or, if you would like to cancel this upload, tap the  button on your phone..
        /// </summary>
        public static string UploadingHelpText {
            get {
                return ResourceManager.GetString("UploadingHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading....
        /// </summary>
        public static string UploadingMessageText {
            get {
                return ResourceManager.GetString("UploadingMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play memos using system player.
        /// </summary>
        public static string UseSystemPlayerCheckboxText {
            get {
                return ResourceManager.GetString("UseSystemPlayerCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
